import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import { cookies } from "next/headers";
import "./globals.css";
import { Providers } from "@/components/providers";
import { AppSplash } from "@/components/app-splash";
import { LANG_COOKIE, DEFAULT_LOCALE, isLocale } from "@/lib/i18n/config";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const SITE_URL = "https://phantomtracker.io";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Phantom Tracker - Habit Tracker with Streaks, Levels & a Living World",
    template: "%s · Phantom Tracker",
  },
  description:
    "A free, dark, minimalist habit tracker. Build daily streaks, earn XP and levels, grow a living world that reflects your consistency, and get reminders that keep you showing up. Works on every device.",
  applicationName: "Phantom Tracker",
  keywords: [
    "habit tracker", "habit app", "daily habits", "streak tracker", "routine tracker",
    "productivity app", "habit building", "free habit tracker", "habit tracker PWA",
  ],
  authors: [{ name: "Phantom Tracker" }],
  creator: "Phantom Tracker",
  manifest: "/manifest.json",
  alternates: { canonical: "/" },
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    shortcut: "/favicon.ico",
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180" }],
  },
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: "Phantom Tracker",
    title: "Phantom Tracker - Habit Tracker with Streaks, Levels & a Living World",
    description:
      "Build daily streaks, earn XP and levels, and grow a living world that reflects your consistency. Free, on every device.",
    // Share image is generated by app/opengraph-image.tsx (1200×630).
  },
  twitter: {
    card: "summary_large_image",
    title: "Phantom Tracker - Habit Tracker with Streaks & Levels",
    description: "A free, dark habit tracker. Streaks, XP, levels, and a living world that grows with you.",
    // Twitter falls back to the generated OpenGraph image.
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1 },
  },
  // Controls the name shown under the icon when added to an iOS Home Screen.
  appleWebApp: {
    capable: true,
    title: "Phantom Tracker",
    statusBarStyle: "black-translucent",
  },
};

export const viewport: Viewport = {
  themeColor: "#0a0a0a",
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieLang = cookies().get(LANG_COOKIE)?.value;
  const lang = isLocale(cookieLang) ? cookieLang : DEFAULT_LOCALE;
  return (
    <html lang={lang} className="dark" suppressHydrationWarning>
      <head>
        {/* Apply the saved accent theme before paint to avoid a flash. */}
        <script
          dangerouslySetInnerHTML={{
            __html: `try{if(localStorage.getItem('pt:theme')==='diamond')document.documentElement.classList.add('theme-diamond')}catch(e){}`,
          }}
        />
      </head>
      <body suppressHydrationWarning className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-white`}>
        <Providers lang={lang}>{children}</Providers>
        <AppSplash />
      </body>
    </html>
  );
}
